---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-xml
  - id: check-merge-conflict
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [ --strict ]

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    args: [ "--severity=error" ]
    exclude: "^.git"
    files: "\\.sh$"

- repo: https://github.com/ansible/ansible-lint
  rev: v25.1.1
  hooks:
  - id: ansible-lint
    additional_dependencies:
    - ansible-core==2.16.4
    - jmespath==1.0.1
    - netaddr==1.3.0
    - distlib

- repo: https://github.com/golangci/misspell
  rev: v0.6.0
  hooks:
  - id: misspell
    exclude: "OWNERS_ALIASES$"

- repo: local
  hooks:
  - id: jinja-syntax-check
    name: jinja-syntax-check
    entry: kubespray/tests/scripts/check-templates.py
    language: python
    types:
    - jinja
    additional_dependencies:
    - jinja2

  - id: propagate-ansible-variables
    name: Update static files referencing default kubespray values
    language: python
    additional_dependencies:
    - ansible-core==2.16.4
    entry: kubespray/scripts/propagate_ansible_variables.yml
    pass_filenames: false

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.12.0
  hooks:
  - id: markdownlint
    exclude: "^.github|(^docs/_sidebar\\.md$)"
