################################################################################
# export REBEL_PYPI_USERNAME=XXXXXXXX REBEL_PYPI_PASSWORD=XXXXXXXX REBEL_R18S_PYPI_USERNAME=XXXXXXXX REBEL_R18S_PYPI_PASSWORD=XXXXXXXX
# export REPO=docker.e2e.sw2.rebellions.in/rebellions-sw/devpack TAG=r18s1
# docker build -t        "$REPO:$TAG" --target full   --secret id=REBEL_PYPI_USERNAME --secret id=REBEL_PYPI_PASSWORD --secret id=REBEL_R18S_PYPI_USERNAME --secret id=REBEL_R18S_PYPI_PASSWORD /
# docker build -t    "$REPO-app:$TAG" --target app    --secret id=REBEL_PYPI_USERNAME --secret id=REBEL_PYPI_PASSWORD --secret id=REBEL_R18S_PYPI_USERNAME --secret id=REBEL_R18S_PYPI_PASSWORD /
# docker build -t  "$REPO-build:$TAG" --target build  --secret id=REBEL_PYPI_USERNAME --secret id=REBEL_PYPI_PASSWORD --secret id=REBEL_R18S_PYPI_USERNAME --secret id=REBEL_R18S_PYPI_PASSWORD /
# docker build -t "$REPO-python:$TAG" --target python --secret id=REBEL_PYPI_USERNAME --secret id=REBEL_PYPI_PASSWORD --secret id=REBEL_R18S_PYPI_USERNAME --secret id=REBEL_R18S_PYPI_PASSWORD /
# docker build -t "$REPO-driver:$TAG" --target driver --secret id=REBEL_PYPI_USERNAME --secret id=REBEL_PYPI_PASSWORD --secret id=REBEL_R18S_PYPI_USERNAME --secret id=REBEL_R18S_PYPI_PASSWORD /

ARG PLATFORM=linux/amd64
FROM --platform=$PLATFORM ubuntu:22.04 AS base

ARG WORKDIR=/workspace
WORKDIR "$WORKDIR"

ARG ATOM_DRIVER_VERSION=2.0.0
ARG RBLN_CCL_VERSION="$ATOM_DRIVER_VERSION"
ARG BCM_DRIVER_VERSION=233.1.135.7
ARG BCM_LIBBNXT_RE_VERSION=233.0.152.2
ARG LLVM_VERSION=19.1.7-rbln
ARG OPTIMUM_RBLN_VERSION=0.7.5rc3.dev3+g0e82798
ARG RAY_VERSION=2.46.0
ARG TORCHVISION_VERSION=0.21.0+cpu
ARG TORCH_VERSION=2.6.0+cpu
ARG REBEL_COMPILER_VERSION=0.8.4.dev102+gd72fde37
ARG TRITON_VERSION=3.2.0+rbln.git47ee49fe
ARG VLLM_RBLN_VERSION=0.8.0rc0
ARG VLLM_VERSION=0.9.1
ARG REBEL_DEPENDENCY_DIR=/mnt/shared_data/users/daekyeong/nas_data/rebel_dependency
ARG ATOM_DRIVER_PACAKGE_DIR=/mnt/shared_data/users/daekyeong/nas_data/pkg
ARG RBLN_CCL_PACAKGE_DIR=/mnt/shared_data/users/daekyeong/nas_data/pkg
ARG PYPI_REPO_URL=https://pypi.e2e.sw2.rebellions.in/simple

LABEL ATOM_DRIVER_VERSION="$ATOM_DRIVER_VERSION"
LABEL RBLN_CCL_VERSION="$RBLN_CCL_VERSION"
LABEL BCM_DRIVER_VERSION="$BCM_DRIVER_VERSION"
LABEL BCM_LIBBNXT_RE_VERSION="$BCM_LIBBNXT_RE_VERSION"
LABEL LLVM_VERSION="$LLVM_VERSION"
LABEL OPTIMUM_RBLN_VERSION="$OPTIMUM_RBLN_VERSION"
LABEL RAY_VERSION="$RAY_VERSION"
LABEL REBEL_COMPILER_VERSION="$REBEL_COMPILER_VERSION"
LABEL TORCHVISION_VERSION="$TORCHVISION_VERSION"
LABEL TORCH_VERSION="$TORCH_VERSION"
LABEL VLLM_RBLN_VERSION="$VLLM_RBLN_VERSION"
LABEL REBEL_DEPENDENCY_DIR="$REBEL_DEPENDENCY_DIR"
LABEL ATOM_DRIVER_PACAKGE_DIR="$ATOM_DRIVER_PACAKGE_DIR"
LABEL RBLN_CCL_PACAKGE_DIR="$RBLN_CCL_PACAKGE_DIR"


RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g; s/kr.archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list && \
  sed -i 's/security.ubuntu.com/mirror.kakao.com/g; s/kr.security.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list

################################################################################
FROM base AS bnxt

RUN PYTHONUNBUFFERED=1 DEBIAN_FRONTEND=noninteractive apt update && \
  apt install -y \
    autoconf \
    automake \
    build-essential \
    gcc \
    iproute2 \
    kmod \
    libibverbs-dev \
    librdmacm-dev \
    librdmacm1 \
    libtool \
    pciutils \
    python3 \
    systemd \
    wget && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

RUN wget "https://docs.broadcom.com/docs-and-downloads/ethernet-network-adapters/NXE/BRCM_$BCM_DRIVER_VERSION/bcm_$BCM_DRIVER_VERSION.tar.gz" && \
  tar -xvzf "bcm_$BCM_DRIVER_VERSION.tar.gz" && \
  tar -C /tmp -xf "$WORKDIR/bcm_$BCM_DRIVER_VERSION/drivers_linux/bnxt_rocelib/libbnxt_re-$BCM_LIBBNXT_RE_VERSION.tar.gz" && \
  cd "/tmp/libbnxt_re-$BCM_LIBBNXT_RE_VERSION" && \
  sh autogen.sh && \
  ./configure && \
  make clean && \
  make && \
  make install


FROM base AS atom

ARG ATOM_DRIVER_PACKAGE="atom_internal_release_${ATOM_DRIVER_VERSION}_amd64.deb"
COPY "$ATOM_DRIVER_PACAKGE_DIR/$ATOM_DRIVER_PACKAGE" "/atom/$ATOM_DRIVER_PACKAGE"
RUN dpkg-deb --vextract "/atom/$ATOM_DRIVER_PACKAGE" /atom/ && rm -f "/atom/$ATOM_DRIVER_PACKAGE"

ARG RBLN_CCL_PACKAGE="librbln-ccl2_${RBLN_CCL_VERSION}_amd64.deb"
ARG RBLN_CCL_DEV_PACKAGE="librbln-ccl-dev_${RBLN_CCL_VERSION}_amd64.deb"
COPY "$RBLN_CCL_PACAKGE_DIR/$RBLN_CCL_PACKAGE" "/atom/$RBLN_CCL_PACKAGE"
COPY "$RBLN_CCL_PACAKGE_DIR/$RBLN_CCL_DEV_PACKAGE" "/atom/$RBLN_CCL_DEV_PACKAGE"
RUN dpkg-deb --vextract "/atom/$RBLN_CCL_PACKAGE" /atom/ && rm -f "/atom/$RBLN_CCL_PACKAGE"
RUN dpkg-deb --vextract "/atom/$RBLN_CCL_DEV_PACKAGE" /atom/ && rm -f "/atom/$RBLN_CCL_DEV_PACKAGE"


################################################################################
FROM base AS driver

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/bash"]

RUN PYTHONUNBUFFERED=1 DEBIAN_FRONTEND=noninteractive apt update && \
  apt install -y \
    tini \
    libbz2-1.0 \
    libcmocka0 \
    libdrm2 \
    libibverbs1 \
    librdmacm1 \
    rdma-core \
    zlib1g && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

COPY --from=bnxt /usr/local/lib/libbnxt_re-rdmav34.so /usr/local/lib/libbnxt_re-rdmav34.so
RUN mv /usr/lib/x86_64-linux-gnu/libibverbs/libbnxt_re-rdmav34.so /usr/lib/x86_64-linux-gnu/libibverbs/libbnxt_re-rdmav34.so.inbox && \
  ln -s /usr/local/lib/libbnxt_re-rdmav34.so /usr/local/lib/libbnxt_re.so && \
  ldconfig

COPY --from=atom /atom/etc/ /etc/
COPY --from=atom /atom/opt/ /opt/
COPY --from=atom /atom/usr/ /usr/
COPY --from=atom /atom/lib/ /usr/

################################################################################
FROM driver AS python

RUN PYTHONUNBUFFERED=1 DEBIAN_FRONTEND=noninteractive apt update && \
  apt install -y \
    python3-pip \
    python3-distutils \
    python3-venv \
    python-is-python3 && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*


################################################################################
FROM python AS vllm-build

RUN PYTHONUNBUFFERED=1 DEBIAN_FRONTEND=noninteractive apt update && \
  apt install -y \
    git wget rsync ssh && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

ARG PYPI_REPO_URL
RUN --mount=type=secret,id=REBEL_PYPI_USERNAME,env=REBEL_PYPI_USERNAME \
    --mount=type=secret,id=REBEL_PYPI_PASSWORD,env=REBEL_PYPI_PASSWORD \
    python3 -m venv $WORKDIR/.venv && . $WORKDIR/.venv/bin/activate \
    #&& pip install poetry==2.0.1 --no-cache  \
    #&& poetry init -n --python '>=3.10,<3.13' \
    #&& poetry source add rbln-r18s --priority supplemental -- https://pypi.e2e.sw2.rebellions.in/simple \
    #&& poetry source add rbln --priority supplemental -- https://pypi.rebellions.in/simple \
    #&& poetry source add torch --priority supplemental -- https://download.pytorch.org/whl/cpu \
    #&& poetry config http-basic.rbln-r18s "$REBEL_R18S_PYPI_USERNAME" "$REBEL_R18S_PYPI_PASSWORD" \
    #&& poetry config http-basic.rbln "$REBEL_PYPI_USERNAME" "$REBEL_PYPI_PASSWORD" \
    #&& poetry config virtualenvs.create false \
    #&& poetry sync --no-root --no-cache \ 
    && pip install --no-cache torch==2.7.0+cpu -i https://download.pytorch.org/whl/cpu \
    && pip install --no-cache torch-rbln==0.1.1 --extra-index-url "$PYPI_REPO_URL" \

RUN pip install --no-cache build \
    && git clone https://github.com/rebellions-sw/vllm-rbln.git \
    && cd vllm-rbln \
    && git checkout main \
    && git submodule update --init --recursive \
    && python -m build --wheel \
    && pip install --no-cache dist/*.whl \
    && pip install --no-cache rebel_compiler=="$REBEL_COMPILER_VERSION" --extra-index-url "$PYPI_REPO_URL" \
    && pip install --no-cache triton=="$TRITON_VERSION" --extra-index-url "$PYPI_REPO_URL" \
    && pip install --no-cache "numpy<2" \ 
    && rm -rf $WORKDIR/vllm-rbln
